Write Fee values to oracle
fabriqnetwork/magi pull request #22
Opened 2023-11-27 15:47 UTC by siosw

Magi should update `l1FeeOverhead` and `l1FeeScalar` in the oracle

2023-12-02 00:56 UTC, LEAFERx requested changes
lets wait for #23 before merge

2023-12-02 00:56 UTC, LEAFERx commented on src/specular/sequencing/mod.rs
> +            U256::from(4242),
`AttributesBuilder` holds the `config` so you can read directly

2023-12-05 19:33 UTC, ujvl approved these changes

2023-12-07 09:31 UTC, LEAFERx approved these changes

2023-12-07 09:31 UTC, merged